"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "./components/app-shell";
import { createClient } from "@/lib/supabase/client";
import type { Tables } from "@/packages/database/src/database.types";
import { average, bangkokMonth, delta, money, monthRange, previousMonth, totalRows, weight } from "@/lib/analytics";
import { thaiDate } from "@/lib/sales";
import { ThaiMonthInput } from "./components/thai-month-input";
import "./dashboard.css";
import "./components/thai-month-input.css";

type Farm = Tables<"farms">; type Sale = Tables<"sales">;
export default function DashboardPage() {
 const [month, setMonth] = useState(bangkokMonth()); const [farmId, setFarmId] = useState(""); const [farms, setFarms] = useState<Farm[]>([]); const [current, setCurrent] = useState({ total: 0n, weight: 0n, count: 0n, owner: 0n, worker: 0n }); const [previous, setPrevious] = useState({ total: 0n, weight: 0n, count: 0n, owner: 0n, worker: 0n }); const [farmSummaries, setFarmSummaries] = useState<Array<{ farm_id: string; total_amount: number; weight_kg: number; sale_count: number; owner_share: number; worker_share: number }>>([]); const [latest, setLatest] = useState<Sale[]>([]); const [status, setStatus] = useState("กำลังโหลดข้อมูล…");
 const load = useCallback(async () => { setStatus("กำลังโหลดข้อมูล…"); const client = createClient(); const now = monthRange(month), before = monthRange(previousMonth(month)); let latestQuery = client.from("sales").select("*").gte("sale_date", now.start).lt("sale_date", now.end).order("sale_date", { ascending: false }).order("id", { ascending: false }).limit(4); if (farmId) latestQuery = latestQuery.eq("farm_id", farmId); const [farmResult, nowResult, beforeResult, salesResult, allFarmResult] = await Promise.all([client.from("farms").select("*").order("name"), client.rpc("sales_summary", { p_start: now.start, p_end: now.end, p_farm_id: farmId || undefined }), client.rpc("sales_summary", { p_start: before.start, p_end: before.end, p_farm_id: farmId || undefined }), latestQuery, client.rpc("sales_summary", { p_start: now.start, p_end: now.end })]); if (farmResult.data) setFarms(farmResult.data); if (nowResult.error || beforeResult.error || salesResult.error || allFarmResult.error) { setStatus("โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่"); return; } setCurrent(totalRows(nowResult.data ?? [])); setPrevious(totalRows(beforeResult.data ?? [])); setFarmSummaries(allFarmResult.data ?? []); setLatest(salesResult.data ?? []); setStatus(""); }, [farmId, month]);
 useEffect(() => { void load(); }, [load]); const avg = average(current), priorAvg = average(previous); const names = useMemo(() => Object.fromEntries(farms.map((farm) => [farm.id, farm.name])), [farms]); const todayMonth = bangkokMonth() === month;
 const cards = [{ label:"ยอดขาย", value:`${money(current.total)} บาท`, change:delta(current.total, previous.total) },{ label:"น้ำหนักรวม", value:`${weight(current.weight)} kg`, change:delta(current.weight, previous.weight) },{ label:"ราคาเฉลี่ย/kg", value:avg === null ? "—" : `${money(avg)} บาท`, change:avg === null || priorAvg === null ? "ไม่มีฐานเปรียบเทียบ" : delta(avg, priorAvg) },{ label:"จำนวนครั้งที่ขาย", value:`${current.count.toString()} ครั้ง`, change:delta(current.count, previous.count) }];
 return <AppShell active="overview" title="ภาพรวม"><section className="page-intro"><div><p>ติดตามยอดขายของฟาร์มในช่วงเวลาที่เลือก</p><span className="period-chip">{todayMonth ? "ยอดสะสมถึงวันนี้ เทียบเดือนก่อนเต็มเดือน" : "เทียบกับเดือนก่อนหน้า"}</span></div><Link className="button primary" href="/sales/new">+ บันทึกการขาย</Link></section><section className="filter-row"><label>ฟาร์ม<select value={farmId} onChange={(event) => setFarmId(event.target.value)}><option value="">ทุกฟาร์มที่มีสิทธิ์</option>{farms.map((farm) => <option key={farm.id} value={farm.id}>{farm.name}</option>)}</select></label><label>เดือน<ThaiMonthInput value={month} onChange={setMonth} /></label></section>{status ? <section className="empty-state"><p>{status}</p></section> : <><section className="kpi-grid" aria-label="ตัวชี้วัดหลัก">{cards.map((card) => <article className="kpi-card" key={card.label}><p>{card.label}</p><strong>{card.value}</strong><span>{card.change}</span></article>)}</section><section className="two-column"><section className="panel"><h2>ส่วนแบ่งรายได้</h2><div className="income-line"><span>เจ้าของ</span><b>{money(current.owner)} บาท</b></div><div className="income-line"><span>ลูกจ้าง</span><b>{money(current.worker)} บาท</b></div><p className="muted">รวมจากทุกรายการในช่วงที่เลือก</p></section><section className="panel"><h2>ยอดขายแต่ละฟาร์ม</h2>{farmSummaries.length === 0 ? <p className="muted">ยังไม่มีรายการขายในช่วงนี้</p> : <div className="latest-list">{farmSummaries.map((row) => <div key={row.farm_id}><span>{names[row.farm_id] ?? "ฟาร์ม"}</span><b>{money(totalRows([row]).total)} บาท</b></div>)}</div>}</section></section><section className="panel"><h2>รายการล่าสุด</h2>{latest.length === 0 ? <p className="muted">ยังไม่มีรายการขายในช่วงนี้</p> : <div className="latest-list">{latest.map((sale) => <Link key={sale.id} href={`/sales/${sale.id}`}><span>{thaiDate(sale.sale_date)} · {names[sale.farm_id] ?? "ฟาร์ม"}</span><b>{Number(sale.total_amount ?? 0).toLocaleString("th-TH", { minimumFractionDigits:2, maximumFractionDigits:2 })} บาท</b></Link>)}</div>}</section></>}</AppShell>;
}
